### ISSUE TITLE
typo fix

### ISSUE THREAD

**Issue by faaliyet** [eousphoros/mod-spdy#31]
in readme file;
```
    If everything is successful you should have mod-spdy/src/out/Release/libmod_spdy.so and /mod-spdy/src/mod_ssl.so which can be installed into your apache2.4 modules directory.
```

Did you mean mod-spdy/src/mod_ssl.so (without slash) ?
I didn't test and even this fix is not important, I think it can help to some users.
I found this in my automated bash script, which is coded without test ((:

**Comment by eousphoros** [comment]
Thank you for the heads up. Updated the readme file in the three branches.
