### ISSUE TITLE
SPDY 3.1 support

### ISSUE THREAD

**Issue by szepeviktor** [eousphoros/mod-spdy#38]
@eousphoros Do you plan to go on with this project?

**Comment by szepeviktor** [comment]
5-9 months: https://svn.apache.org/viewvc/httpd/mod_spdy/trunk/

**Comment by v998** [comment]
I guess mod-spdy is just a port for Apache 2.4 of the original mod_spdy (from Google, for Apache 2.2)
But I don't think the [2.2 mod_spdy] will support SPDY 3.1
Actually I remember once this project have advertised SPDY3.1 in the NPN...but there was some problems with 3.1...(it should be HTTP POST...)

Also the https://svn.apache.org/viewvc/httpd/mod_spdy/trunk/ is forked from this repo...

**Comment by eousphoros** [comment]
The rub is now that HTTP/2 has been finalized the purpose spdy was initially built to solve has been accomplished. Now we need to look forward to the actual implementations of HTTP/2 onward imo.

**Comment by szepeviktor** [comment]
Thank you!
Until then I try https://github.com/tatsuhiro-t/nghttp2.
