### ISSUE TITLE
spdy/3 support removed from browsers

### ISSUE THREAD

**Issue by antoinedeschenes** [eousphoros/mod-spdy#51]
Edge, Firefox and Chrome stopped supporting spdy/3 it seems. 

Chrome 44 and Firefox 41 still support spdy/3.1 as of today. 

chrome://net-internals/#http2 gives:
Next Protocols: http/1.1,spdy/3.1,h2-14,h2

Enabling spdy/3.1 advertising allows to use spdy again on all of those browsers.

**Comment by v998** [comment]
mod-spdy does not actually support spdy/3.1

it had once advertised it but it cause problems with HTTP POST... see earlier issues..


actually you can do some code modifications in `mod_spdy.cc` to advertise it...

see https://github.com/eousphoros/mod-spdy/commit/3068e15d02e48fb5efe1ab8fa53f7ddf0a380b58
